In Java, any statement that might throw an exception can be caught using `try ... catch`. Place the statements that might cause an exception in `try { ... }`, and then use `catch` to capture the corresponding `Exception` and its subclasses.

### **Multiple Catch Statements**
You can use multiple `catch` statements, each catching the corresponding `Exception` and its subclasses. When an exception is caught, the JVM matches the `catch` statements from top to bottom. Once a match is found, it executes that `catch` block and <mark style="background: #BBFABBA6;">does not continue matching</mark>.

Simply put: only one of the multiple `catch` statements can be executed. For example:

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println(e);
    } catch (NumberFormatException e) {
        System.out.println(e);
    }
}
```
When there are multiple `catch` blocks, the order of the `catch` blocks is crucial: the subclass must be written before its superclass. For instance:

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println("IO error");
    } catch (UnsupportedEncodingException e) { // Will never be caught
        System.out.println("Bad encoding");
    }
}
```
In the above code, the `UnsupportedEncodingException` will never be caught because it is a subclass of `IOException`. When an `UnsupportedEncodingException` is thrown, it will be caught by `catch (IOException e) { ... }`.

Therefore, the correct way is to place the subclass before the superclass:

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    }
}
```

### **Finally Statement**
What if we always want to execute some statements, regardless of whether an exception occur.

We can write the execution statement several times: place it in `try` for normal execution, and repeat it in each `catch`. For example:

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
        System.out.println("END");
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
        System.out.println("END");
    } catch (IOException e) {
        System.out.println("IO error");
        System.out.println("END");
    }
}
```
The above code will execute `System.out.println("END");` whether an exception occurs or not.

To eliminate these repetitive codes, Java's `try ... catch` mechanism also provides the `finally` statement. `finally` ensures execution whether an error occurs or not. The above code can be rewritten as follows:

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    } finally {
        System.out.println("END");
    }
}
```
Note that `finally` has several characteristics:

- `finally` is not mandatory, it can be omitted.
- `finally` is always executed last.
  
If no exception occurs, `try { ... }` is executed normally, followed by `finally`. If an exception occurs, execution of `try { ... }` is interrupted, the matching `catch` block is executed, and finally `finally` is executed.

Thus, `finally` is used to guarantee that some code must be executed.

In some cases, there might be no `catch`, only using `try ... finally`. For example:

```java
void process(String file) throws IOException {
    try {
        ...
    } finally {
        System.out.println("END");
    }
}
```
Since the method declares the potential exceptions, `catch` can be omitted.

### **Catching Multiple Exceptions**
If some exceptions have the same handling logic but do not have an inheritance relationship, then multiple `catch` clauses need to be written:

```java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println("Bad input");
    } catch (NumberFormatException e) {
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```
Since the handling code for `IOException` and `NumberFormatException` is the same, we can merge them using `|`:

```java
public static void main(String[] args) {


    try {
        process1();
        process2();
        process3();
    } catch (IOException | NumberFormatException e) { // Either IOException or NumberFormatException
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```